Traceback (most recent call last):
  File "/Users/zoangrak/Documents/대외활동/프로젝트/woohakjung/app.py", line 3, in <module>
    from openai import OpenAI
ModuleNotFoundError: No module named 'openai'
Traceback (most recent call last):
  File "/Users/zoangrak/Documents/대외활동/프로젝트/woohakjung/app.py", line 3, in <module>
    from openai import OpenAI
ModuleNotFoundError: No module named 'openai'
Traceback (most recent call last):
  File "/Users/zoangrak/Documents/대외활동/프로젝트/woohakjung/app.py", line 3, in <module>
    from openai import OpenAI
ModuleNotFoundError: No module named 'openai'
Traceback (most recent call last):
  File "/Users/zoangrak/Documents/대외활동/프로젝트/woohakjung/app.py", line 3, in <module>
    from openai import OpenAI
ModuleNotFoundError: No module named 'openai'
nohup: python: No such file or directory
